apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: default # here can namespace be declared in which the ressource is created and accessible. for default this doesn't need to be defined here. this is just an example. (volumes can not be created in namespaces. they are global accessable)
data:
  database_url: mongodb-service # to access a service from another namespase, namespace name can be attached after a dot. mongodb.service.myNamespace