apiVersion: v1 #secrets should no be defined in configmaps. Here in Secret data can be encoded (here base64)
kind: Secret
metadata:
  name: mongodb-secret
type: opaque
data:
  mongo-root-username: dGVzdHVzZXI= # base64
  mongo-root-password: dGVzdHBhc3N3b3Jk # base64